config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'
  get 'about', to: 'jobs#about'
  resources :jobs

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :jobs
	validates_uniqueness_of :email
end

app/models/job.rb
class Job < ActiveRecord::Base
  INDUSTRIES = ['Outdoors', 'Snow', 'Action', 'Bike', 'Fitness', 'Fishing', 'Hunting/Shooting']
  CATEGORIES = ['Design']
  POSITION_TYPES = ['Full Time', 'Part Time', 'Seasonal', 'Contract', 'Hourly', 'Freelance', 'Intern']

	belongs_to :account
	validates :url, :url => {:no_local => true}
	scope :active, -> { where('created_at > ?', 30.days.ago) }
	delegate :name, to: :account, prefix: true

  enum :industry => INDUSTRIES
  enum :job_category => CATEGORIES
  enum :position_type => POSITION_TYPES

  def days_left
 		((created_at + 30.days - DateTime.now)/86400).round
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all.active.order('created_at DESC')
	end

	def show
		@job = Job.find(params[:id])
	end

	def new
		@job = Job.new
	end

	def create
		@job = job_manager
		if @job.save
			redirect_to root_path
		else
			redirect_to :back, :flash => {:error => "Your URL must look like http://www.example.com"}
		end
	end

	private

		def job_manager
			JobManager.new(job_params, account_params).perform
		end

		def job_params
			params.require(:job).permit(:title, :location, :url, :company, :description, :industry, :job_category, :position_type)
		end

		def account_params
			params.require(:account).permit(:name, :email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/about.html.haml
#front-landing
  .jumbotron.tall{:style=>"background-image:url('https://scontent-lax3-1.xx.fbcdn.net/hphotos-xpa1/t31.0-8/11728889_1048768568489379_1840094476535132507_o.jpg');background-size:cover;"}
    .container
      .row.nav.color-white
        .col-md-8
          .logomark
            =link_to 'Best Outdoor Jobs', '/'
        .col-md-4

          =link_to new_job_path do
            .btn.btn-lg.btn-success.fr
              POST A JOB
          =link_to 'About', about_path, :class => 'fr m2r'
          =link_to 'Blog', 'outdoorjobs.tumblr.com', :class => 'fr m2r'
    .row
      .col-md-7.col-centered.pad4t
        %h1.job-title.fadeInDown.animated.text-shadow
          Mostly, we just want to help people find rad jobs in the outdoor industry



  .container.fill-white{:style=>"width: 100%;"}
    .row
      .col-md-7.col-centered
        %h2.pad4t
          This is a section title
        %p.longform.pad8b
          It's pretty simple. People are more interested than ever in pursuing careers that align with their passions. We want to connect people who want to work in the outdoor industry with the companies that need them.
        %h2
          Why should you post?
        %p.longform.pad8b
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod nulla, ab est. Ad in reprehenderit eligendi dignissimos eveniet sit architecto, voluptatem sed eius. Voluptatum perferendis tenetur iure placeat dignissimos quis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod nulla, ab est. Ad in reprehenderit eligendi dignissimos eveniet sit architecto, voluptatem sed eius. Voluptatum perferendis tenetur iure placeat dignissimos quis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod nulla, ab est. Ad in reprehenderit eligendi dignissimos eveniet sit architecto, voluptatem sed eius. Voluptatum perferendis tenetur iure placeat dignissimos quis!
        %h2
          Who are you?
        %p.longform.pad8b
          Just two friends who love the outdoors and saw an oppportunity to build something that could be useful for a lot of people.
        %h3
          I have multiple jobs I'd like to post. Is there a volume discount?
        %p.longform.pad4b
          Shoot us an email, and we'll chat. We can arrange volume discounts based on the number of jobs you plan to post.
        %h3
          I have multiple jobs I'd like to post. Is there a volume discount?
        %p.longform
          Shoot us an email, and we'll chat. We can arrange volume discounts based on the number of jobs you plan to post.

app/views/jobs/index.html.haml
.shadow
  #front-landing
    .jumbotron.mob-pad2{:style => "background: url('https://scontent-lax3-1.xx.fbcdn.net/hphotos-xpa1/t31.0-8/11728889_1048768568489379_1840094476535132507_o.jpg');background-size:cover;"}
      .container
        .row.nav.color-white
          .col-md-8
            .logomark
              Best Outdoor Jobs
          .col-md-4

            =link_to new_job_path do
              .btn.btn-lg.btn-success.fr
                POST A JOB
            =link_to 'About', about_path, :class => 'fr m2r'
            =link_to 'Blog', 'https://www.theoutbound.com', :class => 'fr m2r'
        .row
          .col-md-8
            %h1.title.color-white.text-shadow
              Find the best jobs in the outdoor industry.

  .container.fill-white{:style=>"width: 100%;"}
    -@jobs.each do |job|
      =link_to job_path(job) do
        .row
          .job.mob-pad2
            .col-md-1.flush
              =image_tag('https://source.unsplash.com/category/nature/112x112')
            .col-md-5.flush
              .content
                .hook
                  %strong
                    =job.title
                .description
                  =job.company
            .col-md-3.flush
              .content
                .location.pad1t
                  =job.location
            .col-md-2.flush
              .content
                .timer.pad1t
                  =job.days_left
                  days left
            .col-md-1.flush.visible-lg
              .content
                .social.pad1t.pull-right

app/views/jobs/new.html.haml
.shadow
  #new-landing
  .container.wide
    .row
      .col-md-12.fill-white.pad5.mob-pad2{:style => "background: url(#{image_path('white-mtn.jpg')});background-size:cover;"}
        .row
          .col-md-5
            %h2.pad3b
              Connect with passionate people looking for work in the outdoor industry.
            %ul.font18
              %li
                %strong $100 per job posting (30 days)
              %li
                One Job per ad please
              %li
                We reserve the right to remove any job or ad early for any reason
              %li
                If we remove your ad we'll refund you the prorated remaining fee
              %li
                Other than ads that are removed, there are no other refunds
          .col-md-1
          .col-md-6
            -if flash[:error].present?
              .alert.alert-danger
                %a.close{:data => {:dismiss => 'alert'}}
                  &times
                =flash[:error]

            =form_for @job, :action => :post do |f|
              .col-md-12.form-group
                %label Job Title
                =f.text_field :title, :placeholder => 'Ex. Chief Marketing Wizard, Lift Operator', :class => 'form-control', :required => true

              .col-md-12.form-group
                %label Location (if remote, put "Remote OK")
                =f.text_field :location, :placeholder => 'Location', :class => 'form-control', :required => true

              .col-md-12.form-group
                %label Where should this link to?
                =f.text_field :url, :placeholder => 'URL to the full job posting or contact form', :class => 'form-control', :required => true


              .col-md-12.form-group
                .row
                  .col-md-4
                    %label
                      %small
                        Industry
                    =select_tag :industry, options_for_select(Job.industries)
                  .col-md-4
                    %label
                      %small
                        Category
                    =select_tag :job_category, options_for_select(Job.job_categories)
                  .col-md-4
                    %label
                      %small
                        Position Type
                    =select_tag :position_type, options_for_select(Job.position_types)

              .col-md-12.form-group
                %label Job Description
                =f.text_area :description, :rows => 20, :placeholder => 'Enter a brief description about the job. Use Markdown styles for formatting.', :class => 'form-control', :required => true



              .col-md-12.form-group
                %label Your Contact Info
                =text_field_tag '[account][name]', nil ,:placeholder => 'Your Name', :class => 'form-control', :required => true

              .col-md-12.form-group
                =text_field_tag '[account][email]', nil ,:placeholder => 'Your Email', :class => 'form-control', :required => true

              .col-md-12.form-group
                %label Company
                =f.text_field :company, :placeholder => 'ACME Outdoors', :class => 'form-control', :required => true

              .col-md-12.form-group
                %label Company Website
                =f.text_field :url, :placeholder => 'http://www.acmeoutdoors.com', :class => 'form-control', :required => true

              .col-md-12
                =f.submit :class=>'btn btn-lg btn-success', :value => 'Post Job'


:javascript
  $( "select" ).select2({});

app/views/jobs/show.html.haml
#front-landing
  .jumbotron.short{:style=>"background-image:url('https://scontent-lax3-1.xx.fbcdn.net/hphotos-xpa1/t31.0-8/11728889_1048768568489379_1840094476535132507_o.jpg');"}
    .container
      .row.nav.color-white
        .col-md-8
          .logomark
            =link_to 'Best Outdoor Jobs', '/'
        .col-md-4

          =link_to new_job_path do
            .btn.btn-lg.btn-success.fr
              POST A JOB
          =link_to 'About', about_path, :class => 'fr m2r'
          =link_to 'Blog', 'http://www.outdoorjobs.tumblr.com', :class => 'fr m2r'



  .container.fill-white{:style=>"width: 100%;"}
    .col-md-12.pad5.mob-pad2
      .row
        .col-md-8
          %h2.upcase.fadeInLeft.animated
            =@job.title
          %p
            =@job.created_at
          .pad8b
            .col-md-6.flush
              %label.color-gray Company
              %h3.m00
                =@job.company
            .col-md-6.flush
              %label.color-gray Location
              %h3.m00
                =@job.location
          %p.longform.m3t
            =@job.description
          .apply
            %h4 How to Apply:
            %p
              =@job.url
        .col-md-2.col-md-offset-1
          .thing{"data-offset-top" => "170", "data-spy" => "affix"}
            .btn.twitter.m1b
              %i.fa.fa-twitter-square.m1r
              Share on Twitter
            .btn.facebook.m1b
              %i.fa.fa-facebook-square.m1r
              Share on Facebook
            .btn.linkedin.m1b
              %i.fa.fa-linkedin-square.m1r
              Post to Linkedin

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Best Outdoor Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="//use.typekit.net/gjg3iwg.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72262694-1', 'auto');
  ga('send', 'pageview');

</script>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>